### ISSUE TITLE
Merge strategy for lists

### ISSUE THREAD

**Issue by nlopin** [victorherraiz/cloud-config-client#25]
Hi Victor!

I've noticed that the default merging strategy for keys that have a list as a value is "merge with overwriting". 
For example, I have two property sources: `default` and `live`. 

```
# default.yml

showMessage:
  roles:
    - admin
    - moderator
    - supervisor

# live.yml

showMessage:
  roles:
    - mama

```

If I call `config.get('showMessage.roles')` for live profile the response will be `['mama', 'moderator', 'supervisor']`. 

I think in general this case is needed more rarely, compared with the "replace" merge strategy. Which would respond with `['mama']`.

Do you think it makes sense to replace it or have an option to chose the strategy? I can help with the implementation
