### ISSUE TITLE
Getting undefined when get json object

### ISSUE THREAD

**Issue by luiscoms** [victorherraiz/cloud-config-client#29]
I am trying to get whole property like json like the example:

Config:

```yml
some:
  property:
    inner: "value"
```

Expected:
```javascript
const data = config.get('some.property');
console.log(data);
// {inner:"value"}
```

Got:
```javascript
const data = config.get('some.property');
console.log(data);
// undefined
```
